/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopCheckoutRouteImport } from './routes/shop.checkout'
import { Route as ShopCartRouteImport } from './routes/shop.cart'
import { Route as AuthenticatedWarehousesRouteImport } from './routes/_authenticated/warehouses'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedToolsImportExportRouteImport } from './routes/_authenticated/tools-import-export'
import { Route as AuthenticatedSystemHealthRouteImport } from './routes/_authenticated/system-health'
import { Route as AuthenticatedSystemRouteImport } from './routes/_authenticated/system'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedStockTransfersRouteImport } from './routes/_authenticated/stock-transfers'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSeedsRouteImport } from './routes/_authenticated/seeds'
import { Route as AuthenticatedSalesRepsRouteImport } from './routes/_authenticated/sales-reps'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedReceiptsRouteImport } from './routes/_authenticated/receipts'
import { Route as AuthenticatedQuotesRouteImport } from './routes/_authenticated/quotes'
import { Route as AuthenticatedPurchasesRouteImport } from './routes/_authenticated/purchases'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedPricingRouteImport } from './routes/_authenticated/pricing'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated/pos'
import { Route as AuthenticatedPesticidesRouteImport } from './routes/_authenticated/pesticides'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedLoyaltyRouteImport } from './routes/_authenticated/loyalty'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedHrRouteImport } from './routes/_authenticated/hr'
import { Route as AuthenticatedFleetRouteImport } from './routes/_authenticated/fleet'
import { Route as AuthenticatedFertilizersRouteImport } from './routes/_authenticated/fertilizers'
import { Route as AuthenticatedEquipmentRouteImport } from './routes/_authenticated/equipment'
import { Route as AuthenticatedDebtsRouteImport } from './routes/_authenticated/debts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCompanySettingsRouteImport } from './routes/_authenticated/company-settings'
import { Route as AuthenticatedChecksRouteImport } from './routes/_authenticated/checks'
import { Route as AuthenticatedCashBoxesRouteImport } from './routes/_authenticated/cash-boxes'
import { Route as AuthenticatedBranchesRouteImport } from './routes/_authenticated/branches'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedBarcodesRouteImport } from './routes/_authenticated/barcodes'
import { Route as AuthenticatedBanksRouteImport } from './routes/_authenticated/banks'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedAgriRouteImport } from './routes/_authenticated/agri'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedAccountingRouteImport } from './routes/_authenticated/accounting'
import { Route as AuthenticatedSystemIndexRouteImport } from './routes/_authenticated/system.index'
import { Route as ShopProductIdRouteImport } from './routes/shop.product.$id'
import { Route as AuthenticatedSystemUsersRouteImport } from './routes/_authenticated/system.users'
import { Route as AuthenticatedSystemPlansRouteImport } from './routes/_authenticated/system.plans'
import { Route as AuthenticatedSystemPermissionsRouteImport } from './routes/_authenticated/system.permissions'
import { Route as AuthenticatedSystemOrganizationsRouteImport } from './routes/_authenticated/system.organizations'
import { Route as AuthenticatedSystemLicensesRouteImport } from './routes/_authenticated/system.licenses'
import { Route as AuthenticatedSystemAuditRouteImport } from './routes/_authenticated/system.audit'
import { Route as AuthenticatedSalesRepsVisitsRouteImport } from './routes/_authenticated/sales-reps.visits'
import { Route as AuthenticatedSalesRepsListRouteImport } from './routes/_authenticated/sales-reps.list'
import { Route as AuthenticatedSalesRepsCommissionsRouteImport } from './routes/_authenticated/sales-reps.commissions'
import { Route as AuthenticatedReportsLiveRouteImport } from './routes/_authenticated/reports.live'
import { Route as AuthenticatedHrPayrollRouteImport } from './routes/_authenticated/hr.payroll'
import { Route as AuthenticatedHrLeavesRouteImport } from './routes/_authenticated/hr.leaves'
import { Route as AuthenticatedHrEmployeesRouteImport } from './routes/_authenticated/hr.employees'
import { Route as AuthenticatedHrDocumentsRouteImport } from './routes/_authenticated/hr.documents'
import { Route as AuthenticatedHrAttendanceRouteImport } from './routes/_authenticated/hr.attendance'
import { Route as AuthenticatedFleetVehiclesRouteImport } from './routes/_authenticated/fleet.vehicles'
import { Route as AuthenticatedFleetTripsRouteImport } from './routes/_authenticated/fleet.trips'
import { Route as AuthenticatedFleetTrackingRouteImport } from './routes/_authenticated/fleet.tracking'
import { Route as AuthenticatedFleetMaintenanceRouteImport } from './routes/_authenticated/fleet.maintenance'
import { Route as AuthenticatedFleetFuelRouteImport } from './routes/_authenticated/fleet.fuel'
import { Route as AuthenticatedFleetDriversRouteImport } from './routes/_authenticated/fleet.drivers'
import { Route as AuthenticatedDashboardsWarehouseRouteImport } from './routes/_authenticated/dashboards.warehouse'
import { Route as AuthenticatedDashboardsSalesRouteImport } from './routes/_authenticated/dashboards.sales'
import { Route as AuthenticatedDashboardsHrRouteImport } from './routes/_authenticated/dashboards.hr'
import { Route as AuthenticatedDashboardsFleetRouteImport } from './routes/_authenticated/dashboards.fleet'
import { Route as AuthenticatedDashboardsFinanceRouteImport } from './routes/_authenticated/dashboards.finance'
import { Route as AuthenticatedDashboardsExecutiveRouteImport } from './routes/_authenticated/dashboards.executive'
import { Route as AuthenticatedAgriTreatmentsRouteImport } from './routes/_authenticated/agri.treatments'
import { Route as AuthenticatedAgriPlantsRouteImport } from './routes/_authenticated/agri.plants'
import { Route as AuthenticatedAgriPestsRouteImport } from './routes/_authenticated/agri.pests'
import { Route as AuthenticatedAgriDiseasesRouteImport } from './routes/_authenticated/agri.diseases'
import { Route as AuthenticatedAccountingTaxesRouteImport } from './routes/_authenticated/accounting.taxes'
import { Route as AuthenticatedAccountingReportsRouteImport } from './routes/_authenticated/accounting.reports'
import { Route as AuthenticatedAccountingPeriodsRouteImport } from './routes/_authenticated/accounting.periods'
import { Route as AuthenticatedAccountingLedgerRouteImport } from './routes/_authenticated/accounting.ledger'
import { Route as AuthenticatedAccountingJournalRouteImport } from './routes/_authenticated/accounting.journal'
import { Route as AuthenticatedAccountingChartRouteImport } from './routes/_authenticated/accounting.chart'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCheckoutRoute = ShopCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ShopRoute,
} as any)
const AuthenticatedWarehousesRoute = AuthenticatedWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolsImportExportRoute =
  AuthenticatedToolsImportExportRouteImport.update({
    id: '/tools-import-export',
    path: '/tools-import-export',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemHealthRoute =
  AuthenticatedSystemHealthRouteImport.update({
    id: '/system-health',
    path: '/system-health',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemRoute = AuthenticatedSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStockTransfersRoute =
  AuthenticatedStockTransfersRouteImport.update({
    id: '/stock-transfers',
    path: '/stock-transfers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeedsRoute = AuthenticatedSeedsRouteImport.update({
  id: '/seeds',
  path: '/seeds',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRepsRoute = AuthenticatedSalesRepsRouteImport.update({
  id: '/sales-reps',
  path: '/sales-reps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReceiptsRoute = AuthenticatedReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotesRoute = AuthenticatedQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchasesRoute = AuthenticatedPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPesticidesRoute = AuthenticatedPesticidesRouteImport.update({
  id: '/pesticides',
  path: '/pesticides',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLoyaltyRoute = AuthenticatedLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHrRoute = AuthenticatedHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFleetRoute = AuthenticatedFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFertilizersRoute =
  AuthenticatedFertilizersRouteImport.update({
    id: '/fertilizers',
    path: '/fertilizers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipmentRoute = AuthenticatedEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDebtsRoute = AuthenticatedDebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompanySettingsRoute =
  AuthenticatedCompanySettingsRouteImport.update({
    id: '/company-settings',
    path: '/company-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChecksRoute = AuthenticatedChecksRouteImport.update({
  id: '/checks',
  path: '/checks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCashBoxesRoute = AuthenticatedCashBoxesRouteImport.update({
  id: '/cash-boxes',
  path: '/cash-boxes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBranchesRoute = AuthenticatedBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBarcodesRoute = AuthenticatedBarcodesRouteImport.update({
  id: '/barcodes',
  path: '/barcodes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBanksRoute = AuthenticatedBanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgriRoute = AuthenticatedAgriRouteImport.update({
  id: '/agri',
  path: '/agri',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountingRoute = AuthenticatedAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSystemIndexRoute =
  AuthenticatedSystemIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSystemRoute,
  } as any)
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => ShopRoute,
} as any)
const AuthenticatedSystemUsersRoute =
  AuthenticatedSystemUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSystemRoute,
  } as any)
const AuthenticatedSystemPlansRoute =
  AuthenticatedSystemPlansRouteImport.update({
    id: '/plans',
    path: '/plans',
    getParentRoute: () => AuthenticatedSystemRoute,
  } as any)
const AuthenticatedSystemPermissionsRoute =
  AuthenticatedSystemPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedSystemRoute,
  } as any)
const AuthenticatedSystemOrganizationsRoute =
  AuthenticatedSystemOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedSystemRoute,
  } as any)
const AuthenticatedSystemLicensesRoute =
  AuthenticatedSystemLicensesRouteImport.update({
    id: '/licenses',
    path: '/licenses',
    getParentRoute: () => AuthenticatedSystemRoute,
  } as any)
const AuthenticatedSystemAuditRoute =
  AuthenticatedSystemAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedSystemRoute,
  } as any)
const AuthenticatedSalesRepsVisitsRoute =
  AuthenticatedSalesRepsVisitsRouteImport.update({
    id: '/visits',
    path: '/visits',
    getParentRoute: () => AuthenticatedSalesRepsRoute,
  } as any)
const AuthenticatedSalesRepsListRoute =
  AuthenticatedSalesRepsListRouteImport.update({
    id: '/list',
    path: '/list',
    getParentRoute: () => AuthenticatedSalesRepsRoute,
  } as any)
const AuthenticatedSalesRepsCommissionsRoute =
  AuthenticatedSalesRepsCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AuthenticatedSalesRepsRoute,
  } as any)
const AuthenticatedReportsLiveRoute =
  AuthenticatedReportsLiveRouteImport.update({
    id: '/live',
    path: '/live',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedHrPayrollRoute = AuthenticatedHrPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthenticatedHrRoute,
} as any)
const AuthenticatedHrLeavesRoute = AuthenticatedHrLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => AuthenticatedHrRoute,
} as any)
const AuthenticatedHrEmployeesRoute =
  AuthenticatedHrEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => AuthenticatedHrRoute,
  } as any)
const AuthenticatedHrDocumentsRoute =
  AuthenticatedHrDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedHrRoute,
  } as any)
const AuthenticatedHrAttendanceRoute =
  AuthenticatedHrAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedHrRoute,
  } as any)
const AuthenticatedFleetVehiclesRoute =
  AuthenticatedFleetVehiclesRouteImport.update({
    id: '/vehicles',
    path: '/vehicles',
    getParentRoute: () => AuthenticatedFleetRoute,
  } as any)
const AuthenticatedFleetTripsRoute = AuthenticatedFleetTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AuthenticatedFleetRoute,
} as any)
const AuthenticatedFleetTrackingRoute =
  AuthenticatedFleetTrackingRouteImport.update({
    id: '/tracking',
    path: '/tracking',
    getParentRoute: () => AuthenticatedFleetRoute,
  } as any)
const AuthenticatedFleetMaintenanceRoute =
  AuthenticatedFleetMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedFleetRoute,
  } as any)
const AuthenticatedFleetFuelRoute = AuthenticatedFleetFuelRouteImport.update({
  id: '/fuel',
  path: '/fuel',
  getParentRoute: () => AuthenticatedFleetRoute,
} as any)
const AuthenticatedFleetDriversRoute =
  AuthenticatedFleetDriversRouteImport.update({
    id: '/drivers',
    path: '/drivers',
    getParentRoute: () => AuthenticatedFleetRoute,
  } as any)
const AuthenticatedDashboardsWarehouseRoute =
  AuthenticatedDashboardsWarehouseRouteImport.update({
    id: '/dashboards/warehouse',
    path: '/dashboards/warehouse',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardsSalesRoute =
  AuthenticatedDashboardsSalesRouteImport.update({
    id: '/dashboards/sales',
    path: '/dashboards/sales',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardsHrRoute =
  AuthenticatedDashboardsHrRouteImport.update({
    id: '/dashboards/hr',
    path: '/dashboards/hr',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardsFleetRoute =
  AuthenticatedDashboardsFleetRouteImport.update({
    id: '/dashboards/fleet',
    path: '/dashboards/fleet',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardsFinanceRoute =
  AuthenticatedDashboardsFinanceRouteImport.update({
    id: '/dashboards/finance',
    path: '/dashboards/finance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardsExecutiveRoute =
  AuthenticatedDashboardsExecutiveRouteImport.update({
    id: '/dashboards/executive',
    path: '/dashboards/executive',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgriTreatmentsRoute =
  AuthenticatedAgriTreatmentsRouteImport.update({
    id: '/treatments',
    path: '/treatments',
    getParentRoute: () => AuthenticatedAgriRoute,
  } as any)
const AuthenticatedAgriPlantsRoute = AuthenticatedAgriPlantsRouteImport.update({
  id: '/plants',
  path: '/plants',
  getParentRoute: () => AuthenticatedAgriRoute,
} as any)
const AuthenticatedAgriPestsRoute = AuthenticatedAgriPestsRouteImport.update({
  id: '/pests',
  path: '/pests',
  getParentRoute: () => AuthenticatedAgriRoute,
} as any)
const AuthenticatedAgriDiseasesRoute =
  AuthenticatedAgriDiseasesRouteImport.update({
    id: '/diseases',
    path: '/diseases',
    getParentRoute: () => AuthenticatedAgriRoute,
  } as any)
const AuthenticatedAccountingTaxesRoute =
  AuthenticatedAccountingTaxesRouteImport.update({
    id: '/taxes',
    path: '/taxes',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingReportsRoute =
  AuthenticatedAccountingReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingPeriodsRoute =
  AuthenticatedAccountingPeriodsRouteImport.update({
    id: '/periods',
    path: '/periods',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingLedgerRoute =
  AuthenticatedAccountingLedgerRouteImport.update({
    id: '/ledger',
    path: '/ledger',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingJournalRoute =
  AuthenticatedAccountingJournalRouteImport.update({
    id: '/journal',
    path: '/journal',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingChartRoute =
  AuthenticatedAccountingChartRouteImport.update({
    id: '/chart',
    path: '/chart',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRouteWithChildren
  '/accounting': typeof AuthenticatedAccountingRouteWithChildren
  '/activity': typeof AuthenticatedActivityRoute
  '/agri': typeof AuthenticatedAgriRouteWithChildren
  '/ai': typeof AuthenticatedAiRoute
  '/banks': typeof AuthenticatedBanksRoute
  '/barcodes': typeof AuthenticatedBarcodesRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/cash-boxes': typeof AuthenticatedCashBoxesRoute
  '/checks': typeof AuthenticatedChecksRoute
  '/company-settings': typeof AuthenticatedCompanySettingsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/debts': typeof AuthenticatedDebtsRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/fertilizers': typeof AuthenticatedFertilizersRoute
  '/fleet': typeof AuthenticatedFleetRouteWithChildren
  '/hr': typeof AuthenticatedHrRouteWithChildren
  '/inventory': typeof AuthenticatedInventoryRoute
  '/loyalty': typeof AuthenticatedLoyaltyRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/pesticides': typeof AuthenticatedPesticidesRoute
  '/pos': typeof AuthenticatedPosRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/products': typeof AuthenticatedProductsRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/quotes': typeof AuthenticatedQuotesRoute
  '/receipts': typeof AuthenticatedReceiptsRoute
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/sales': typeof AuthenticatedSalesRoute
  '/sales-reps': typeof AuthenticatedSalesRepsRouteWithChildren
  '/seeds': typeof AuthenticatedSeedsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stock-transfers': typeof AuthenticatedStockTransfersRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/system': typeof AuthenticatedSystemRouteWithChildren
  '/system-health': typeof AuthenticatedSystemHealthRoute
  '/tools-import-export': typeof AuthenticatedToolsImportExportRoute
  '/users': typeof AuthenticatedUsersRoute
  '/warehouses': typeof AuthenticatedWarehousesRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/shop/': typeof ShopIndexRoute
  '/accounting/chart': typeof AuthenticatedAccountingChartRoute
  '/accounting/journal': typeof AuthenticatedAccountingJournalRoute
  '/accounting/ledger': typeof AuthenticatedAccountingLedgerRoute
  '/accounting/periods': typeof AuthenticatedAccountingPeriodsRoute
  '/accounting/reports': typeof AuthenticatedAccountingReportsRoute
  '/accounting/taxes': typeof AuthenticatedAccountingTaxesRoute
  '/agri/diseases': typeof AuthenticatedAgriDiseasesRoute
  '/agri/pests': typeof AuthenticatedAgriPestsRoute
  '/agri/plants': typeof AuthenticatedAgriPlantsRoute
  '/agri/treatments': typeof AuthenticatedAgriTreatmentsRoute
  '/dashboards/executive': typeof AuthenticatedDashboardsExecutiveRoute
  '/dashboards/finance': typeof AuthenticatedDashboardsFinanceRoute
  '/dashboards/fleet': typeof AuthenticatedDashboardsFleetRoute
  '/dashboards/hr': typeof AuthenticatedDashboardsHrRoute
  '/dashboards/sales': typeof AuthenticatedDashboardsSalesRoute
  '/dashboards/warehouse': typeof AuthenticatedDashboardsWarehouseRoute
  '/fleet/drivers': typeof AuthenticatedFleetDriversRoute
  '/fleet/fuel': typeof AuthenticatedFleetFuelRoute
  '/fleet/maintenance': typeof AuthenticatedFleetMaintenanceRoute
  '/fleet/tracking': typeof AuthenticatedFleetTrackingRoute
  '/fleet/trips': typeof AuthenticatedFleetTripsRoute
  '/fleet/vehicles': typeof AuthenticatedFleetVehiclesRoute
  '/hr/attendance': typeof AuthenticatedHrAttendanceRoute
  '/hr/documents': typeof AuthenticatedHrDocumentsRoute
  '/hr/employees': typeof AuthenticatedHrEmployeesRoute
  '/hr/leaves': typeof AuthenticatedHrLeavesRoute
  '/hr/payroll': typeof AuthenticatedHrPayrollRoute
  '/reports/live': typeof AuthenticatedReportsLiveRoute
  '/sales-reps/commissions': typeof AuthenticatedSalesRepsCommissionsRoute
  '/sales-reps/list': typeof AuthenticatedSalesRepsListRoute
  '/sales-reps/visits': typeof AuthenticatedSalesRepsVisitsRoute
  '/system/audit': typeof AuthenticatedSystemAuditRoute
  '/system/licenses': typeof AuthenticatedSystemLicensesRoute
  '/system/organizations': typeof AuthenticatedSystemOrganizationsRoute
  '/system/permissions': typeof AuthenticatedSystemPermissionsRoute
  '/system/plans': typeof AuthenticatedSystemPlansRoute
  '/system/users': typeof AuthenticatedSystemUsersRoute
  '/shop/product/$id': typeof ShopProductIdRoute
  '/system/': typeof AuthenticatedSystemIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/accounting': typeof AuthenticatedAccountingRouteWithChildren
  '/activity': typeof AuthenticatedActivityRoute
  '/agri': typeof AuthenticatedAgriRouteWithChildren
  '/ai': typeof AuthenticatedAiRoute
  '/banks': typeof AuthenticatedBanksRoute
  '/barcodes': typeof AuthenticatedBarcodesRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/cash-boxes': typeof AuthenticatedCashBoxesRoute
  '/checks': typeof AuthenticatedChecksRoute
  '/company-settings': typeof AuthenticatedCompanySettingsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/debts': typeof AuthenticatedDebtsRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/fertilizers': typeof AuthenticatedFertilizersRoute
  '/fleet': typeof AuthenticatedFleetRouteWithChildren
  '/hr': typeof AuthenticatedHrRouteWithChildren
  '/inventory': typeof AuthenticatedInventoryRoute
  '/loyalty': typeof AuthenticatedLoyaltyRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/pesticides': typeof AuthenticatedPesticidesRoute
  '/pos': typeof AuthenticatedPosRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/products': typeof AuthenticatedProductsRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/quotes': typeof AuthenticatedQuotesRoute
  '/receipts': typeof AuthenticatedReceiptsRoute
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/sales': typeof AuthenticatedSalesRoute
  '/sales-reps': typeof AuthenticatedSalesRepsRouteWithChildren
  '/seeds': typeof AuthenticatedSeedsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stock-transfers': typeof AuthenticatedStockTransfersRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/system-health': typeof AuthenticatedSystemHealthRoute
  '/tools-import-export': typeof AuthenticatedToolsImportExportRoute
  '/users': typeof AuthenticatedUsersRoute
  '/warehouses': typeof AuthenticatedWarehousesRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/shop': typeof ShopIndexRoute
  '/accounting/chart': typeof AuthenticatedAccountingChartRoute
  '/accounting/journal': typeof AuthenticatedAccountingJournalRoute
  '/accounting/ledger': typeof AuthenticatedAccountingLedgerRoute
  '/accounting/periods': typeof AuthenticatedAccountingPeriodsRoute
  '/accounting/reports': typeof AuthenticatedAccountingReportsRoute
  '/accounting/taxes': typeof AuthenticatedAccountingTaxesRoute
  '/agri/diseases': typeof AuthenticatedAgriDiseasesRoute
  '/agri/pests': typeof AuthenticatedAgriPestsRoute
  '/agri/plants': typeof AuthenticatedAgriPlantsRoute
  '/agri/treatments': typeof AuthenticatedAgriTreatmentsRoute
  '/dashboards/executive': typeof AuthenticatedDashboardsExecutiveRoute
  '/dashboards/finance': typeof AuthenticatedDashboardsFinanceRoute
  '/dashboards/fleet': typeof AuthenticatedDashboardsFleetRoute
  '/dashboards/hr': typeof AuthenticatedDashboardsHrRoute
  '/dashboards/sales': typeof AuthenticatedDashboardsSalesRoute
  '/dashboards/warehouse': typeof AuthenticatedDashboardsWarehouseRoute
  '/fleet/drivers': typeof AuthenticatedFleetDriversRoute
  '/fleet/fuel': typeof AuthenticatedFleetFuelRoute
  '/fleet/maintenance': typeof AuthenticatedFleetMaintenanceRoute
  '/fleet/tracking': typeof AuthenticatedFleetTrackingRoute
  '/fleet/trips': typeof AuthenticatedFleetTripsRoute
  '/fleet/vehicles': typeof AuthenticatedFleetVehiclesRoute
  '/hr/attendance': typeof AuthenticatedHrAttendanceRoute
  '/hr/documents': typeof AuthenticatedHrDocumentsRoute
  '/hr/employees': typeof AuthenticatedHrEmployeesRoute
  '/hr/leaves': typeof AuthenticatedHrLeavesRoute
  '/hr/payroll': typeof AuthenticatedHrPayrollRoute
  '/reports/live': typeof AuthenticatedReportsLiveRoute
  '/sales-reps/commissions': typeof AuthenticatedSalesRepsCommissionsRoute
  '/sales-reps/list': typeof AuthenticatedSalesRepsListRoute
  '/sales-reps/visits': typeof AuthenticatedSalesRepsVisitsRoute
  '/system/audit': typeof AuthenticatedSystemAuditRoute
  '/system/licenses': typeof AuthenticatedSystemLicensesRoute
  '/system/organizations': typeof AuthenticatedSystemOrganizationsRoute
  '/system/permissions': typeof AuthenticatedSystemPermissionsRoute
  '/system/plans': typeof AuthenticatedSystemPlansRoute
  '/system/users': typeof AuthenticatedSystemUsersRoute
  '/shop/product/$id': typeof ShopProductIdRoute
  '/system': typeof AuthenticatedSystemIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRouteWithChildren
  '/_authenticated/accounting': typeof AuthenticatedAccountingRouteWithChildren
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/agri': typeof AuthenticatedAgriRouteWithChildren
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/banks': typeof AuthenticatedBanksRoute
  '/_authenticated/barcodes': typeof AuthenticatedBarcodesRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/branches': typeof AuthenticatedBranchesRoute
  '/_authenticated/cash-boxes': typeof AuthenticatedCashBoxesRoute
  '/_authenticated/checks': typeof AuthenticatedChecksRoute
  '/_authenticated/company-settings': typeof AuthenticatedCompanySettingsRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/debts': typeof AuthenticatedDebtsRoute
  '/_authenticated/equipment': typeof AuthenticatedEquipmentRoute
  '/_authenticated/fertilizers': typeof AuthenticatedFertilizersRoute
  '/_authenticated/fleet': typeof AuthenticatedFleetRouteWithChildren
  '/_authenticated/hr': typeof AuthenticatedHrRouteWithChildren
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/loyalty': typeof AuthenticatedLoyaltyRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/pesticides': typeof AuthenticatedPesticidesRoute
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/_authenticated/pricing': typeof AuthenticatedPricingRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/purchases': typeof AuthenticatedPurchasesRoute
  '/_authenticated/quotes': typeof AuthenticatedQuotesRoute
  '/_authenticated/receipts': typeof AuthenticatedReceiptsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRouteWithChildren
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/sales-reps': typeof AuthenticatedSalesRepsRouteWithChildren
  '/_authenticated/seeds': typeof AuthenticatedSeedsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/stock-transfers': typeof AuthenticatedStockTransfersRoute
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/system': typeof AuthenticatedSystemRouteWithChildren
  '/_authenticated/system-health': typeof AuthenticatedSystemHealthRoute
  '/_authenticated/tools-import-export': typeof AuthenticatedToolsImportExportRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/warehouses': typeof AuthenticatedWarehousesRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/shop/': typeof ShopIndexRoute
  '/_authenticated/accounting/chart': typeof AuthenticatedAccountingChartRoute
  '/_authenticated/accounting/journal': typeof AuthenticatedAccountingJournalRoute
  '/_authenticated/accounting/ledger': typeof AuthenticatedAccountingLedgerRoute
  '/_authenticated/accounting/periods': typeof AuthenticatedAccountingPeriodsRoute
  '/_authenticated/accounting/reports': typeof AuthenticatedAccountingReportsRoute
  '/_authenticated/accounting/taxes': typeof AuthenticatedAccountingTaxesRoute
  '/_authenticated/agri/diseases': typeof AuthenticatedAgriDiseasesRoute
  '/_authenticated/agri/pests': typeof AuthenticatedAgriPestsRoute
  '/_authenticated/agri/plants': typeof AuthenticatedAgriPlantsRoute
  '/_authenticated/agri/treatments': typeof AuthenticatedAgriTreatmentsRoute
  '/_authenticated/dashboards/executive': typeof AuthenticatedDashboardsExecutiveRoute
  '/_authenticated/dashboards/finance': typeof AuthenticatedDashboardsFinanceRoute
  '/_authenticated/dashboards/fleet': typeof AuthenticatedDashboardsFleetRoute
  '/_authenticated/dashboards/hr': typeof AuthenticatedDashboardsHrRoute
  '/_authenticated/dashboards/sales': typeof AuthenticatedDashboardsSalesRoute
  '/_authenticated/dashboards/warehouse': typeof AuthenticatedDashboardsWarehouseRoute
  '/_authenticated/fleet/drivers': typeof AuthenticatedFleetDriversRoute
  '/_authenticated/fleet/fuel': typeof AuthenticatedFleetFuelRoute
  '/_authenticated/fleet/maintenance': typeof AuthenticatedFleetMaintenanceRoute
  '/_authenticated/fleet/tracking': typeof AuthenticatedFleetTrackingRoute
  '/_authenticated/fleet/trips': typeof AuthenticatedFleetTripsRoute
  '/_authenticated/fleet/vehicles': typeof AuthenticatedFleetVehiclesRoute
  '/_authenticated/hr/attendance': typeof AuthenticatedHrAttendanceRoute
  '/_authenticated/hr/documents': typeof AuthenticatedHrDocumentsRoute
  '/_authenticated/hr/employees': typeof AuthenticatedHrEmployeesRoute
  '/_authenticated/hr/leaves': typeof AuthenticatedHrLeavesRoute
  '/_authenticated/hr/payroll': typeof AuthenticatedHrPayrollRoute
  '/_authenticated/reports/live': typeof AuthenticatedReportsLiveRoute
  '/_authenticated/sales-reps/commissions': typeof AuthenticatedSalesRepsCommissionsRoute
  '/_authenticated/sales-reps/list': typeof AuthenticatedSalesRepsListRoute
  '/_authenticated/sales-reps/visits': typeof AuthenticatedSalesRepsVisitsRoute
  '/_authenticated/system/audit': typeof AuthenticatedSystemAuditRoute
  '/_authenticated/system/licenses': typeof AuthenticatedSystemLicensesRoute
  '/_authenticated/system/organizations': typeof AuthenticatedSystemOrganizationsRoute
  '/_authenticated/system/permissions': typeof AuthenticatedSystemPermissionsRoute
  '/_authenticated/system/plans': typeof AuthenticatedSystemPlansRoute
  '/_authenticated/system/users': typeof AuthenticatedSystemUsersRoute
  '/shop/product/$id': typeof ShopProductIdRoute
  '/_authenticated/system/': typeof AuthenticatedSystemIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/shop'
    | '/accounting'
    | '/activity'
    | '/agri'
    | '/ai'
    | '/banks'
    | '/barcodes'
    | '/billing'
    | '/branches'
    | '/cash-boxes'
    | '/checks'
    | '/company-settings'
    | '/customers'
    | '/dashboard'
    | '/debts'
    | '/equipment'
    | '/fertilizers'
    | '/fleet'
    | '/hr'
    | '/inventory'
    | '/loyalty'
    | '/notifications'
    | '/pesticides'
    | '/pos'
    | '/pricing'
    | '/products'
    | '/purchases'
    | '/quotes'
    | '/receipts'
    | '/reports'
    | '/sales'
    | '/sales-reps'
    | '/seeds'
    | '/settings'
    | '/stock-transfers'
    | '/suppliers'
    | '/system'
    | '/system-health'
    | '/tools-import-export'
    | '/users'
    | '/warehouses'
    | '/shop/cart'
    | '/shop/checkout'
    | '/shop/'
    | '/accounting/chart'
    | '/accounting/journal'
    | '/accounting/ledger'
    | '/accounting/periods'
    | '/accounting/reports'
    | '/accounting/taxes'
    | '/agri/diseases'
    | '/agri/pests'
    | '/agri/plants'
    | '/agri/treatments'
    | '/dashboards/executive'
    | '/dashboards/finance'
    | '/dashboards/fleet'
    | '/dashboards/hr'
    | '/dashboards/sales'
    | '/dashboards/warehouse'
    | '/fleet/drivers'
    | '/fleet/fuel'
    | '/fleet/maintenance'
    | '/fleet/tracking'
    | '/fleet/trips'
    | '/fleet/vehicles'
    | '/hr/attendance'
    | '/hr/documents'
    | '/hr/employees'
    | '/hr/leaves'
    | '/hr/payroll'
    | '/reports/live'
    | '/sales-reps/commissions'
    | '/sales-reps/list'
    | '/sales-reps/visits'
    | '/system/audit'
    | '/system/licenses'
    | '/system/organizations'
    | '/system/permissions'
    | '/system/plans'
    | '/system/users'
    | '/shop/product/$id'
    | '/system/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/accounting'
    | '/activity'
    | '/agri'
    | '/ai'
    | '/banks'
    | '/barcodes'
    | '/billing'
    | '/branches'
    | '/cash-boxes'
    | '/checks'
    | '/company-settings'
    | '/customers'
    | '/dashboard'
    | '/debts'
    | '/equipment'
    | '/fertilizers'
    | '/fleet'
    | '/hr'
    | '/inventory'
    | '/loyalty'
    | '/notifications'
    | '/pesticides'
    | '/pos'
    | '/pricing'
    | '/products'
    | '/purchases'
    | '/quotes'
    | '/receipts'
    | '/reports'
    | '/sales'
    | '/sales-reps'
    | '/seeds'
    | '/settings'
    | '/stock-transfers'
    | '/suppliers'
    | '/system-health'
    | '/tools-import-export'
    | '/users'
    | '/warehouses'
    | '/shop/cart'
    | '/shop/checkout'
    | '/shop'
    | '/accounting/chart'
    | '/accounting/journal'
    | '/accounting/ledger'
    | '/accounting/periods'
    | '/accounting/reports'
    | '/accounting/taxes'
    | '/agri/diseases'
    | '/agri/pests'
    | '/agri/plants'
    | '/agri/treatments'
    | '/dashboards/executive'
    | '/dashboards/finance'
    | '/dashboards/fleet'
    | '/dashboards/hr'
    | '/dashboards/sales'
    | '/dashboards/warehouse'
    | '/fleet/drivers'
    | '/fleet/fuel'
    | '/fleet/maintenance'
    | '/fleet/tracking'
    | '/fleet/trips'
    | '/fleet/vehicles'
    | '/hr/attendance'
    | '/hr/documents'
    | '/hr/employees'
    | '/hr/leaves'
    | '/hr/payroll'
    | '/reports/live'
    | '/sales-reps/commissions'
    | '/sales-reps/list'
    | '/sales-reps/visits'
    | '/system/audit'
    | '/system/licenses'
    | '/system/organizations'
    | '/system/permissions'
    | '/system/plans'
    | '/system/users'
    | '/shop/product/$id'
    | '/system'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/shop'
    | '/_authenticated/accounting'
    | '/_authenticated/activity'
    | '/_authenticated/agri'
    | '/_authenticated/ai'
    | '/_authenticated/banks'
    | '/_authenticated/barcodes'
    | '/_authenticated/billing'
    | '/_authenticated/branches'
    | '/_authenticated/cash-boxes'
    | '/_authenticated/checks'
    | '/_authenticated/company-settings'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/debts'
    | '/_authenticated/equipment'
    | '/_authenticated/fertilizers'
    | '/_authenticated/fleet'
    | '/_authenticated/hr'
    | '/_authenticated/inventory'
    | '/_authenticated/loyalty'
    | '/_authenticated/notifications'
    | '/_authenticated/pesticides'
    | '/_authenticated/pos'
    | '/_authenticated/pricing'
    | '/_authenticated/products'
    | '/_authenticated/purchases'
    | '/_authenticated/quotes'
    | '/_authenticated/receipts'
    | '/_authenticated/reports'
    | '/_authenticated/sales'
    | '/_authenticated/sales-reps'
    | '/_authenticated/seeds'
    | '/_authenticated/settings'
    | '/_authenticated/stock-transfers'
    | '/_authenticated/suppliers'
    | '/_authenticated/system'
    | '/_authenticated/system-health'
    | '/_authenticated/tools-import-export'
    | '/_authenticated/users'
    | '/_authenticated/warehouses'
    | '/shop/cart'
    | '/shop/checkout'
    | '/shop/'
    | '/_authenticated/accounting/chart'
    | '/_authenticated/accounting/journal'
    | '/_authenticated/accounting/ledger'
    | '/_authenticated/accounting/periods'
    | '/_authenticated/accounting/reports'
    | '/_authenticated/accounting/taxes'
    | '/_authenticated/agri/diseases'
    | '/_authenticated/agri/pests'
    | '/_authenticated/agri/plants'
    | '/_authenticated/agri/treatments'
    | '/_authenticated/dashboards/executive'
    | '/_authenticated/dashboards/finance'
    | '/_authenticated/dashboards/fleet'
    | '/_authenticated/dashboards/hr'
    | '/_authenticated/dashboards/sales'
    | '/_authenticated/dashboards/warehouse'
    | '/_authenticated/fleet/drivers'
    | '/_authenticated/fleet/fuel'
    | '/_authenticated/fleet/maintenance'
    | '/_authenticated/fleet/tracking'
    | '/_authenticated/fleet/trips'
    | '/_authenticated/fleet/vehicles'
    | '/_authenticated/hr/attendance'
    | '/_authenticated/hr/documents'
    | '/_authenticated/hr/employees'
    | '/_authenticated/hr/leaves'
    | '/_authenticated/hr/payroll'
    | '/_authenticated/reports/live'
    | '/_authenticated/sales-reps/commissions'
    | '/_authenticated/sales-reps/list'
    | '/_authenticated/sales-reps/visits'
    | '/_authenticated/system/audit'
    | '/_authenticated/system/licenses'
    | '/_authenticated/system/organizations'
    | '/_authenticated/system/permissions'
    | '/_authenticated/system/plans'
    | '/_authenticated/system/users'
    | '/shop/product/$id'
    | '/_authenticated/system/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShopRoute: typeof ShopRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/checkout': {
      id: '/shop/checkout'
      path: '/checkout'
      fullPath: '/shop/checkout'
      preLoaderRoute: typeof ShopCheckoutRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/cart': {
      id: '/shop/cart'
      path: '/cart'
      fullPath: '/shop/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_authenticated/warehouses': {
      id: '/_authenticated/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof AuthenticatedWarehousesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools-import-export': {
      id: '/_authenticated/tools-import-export'
      path: '/tools-import-export'
      fullPath: '/tools-import-export'
      preLoaderRoute: typeof AuthenticatedToolsImportExportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system-health': {
      id: '/_authenticated/system-health'
      path: '/system-health'
      fullPath: '/system-health'
      preLoaderRoute: typeof AuthenticatedSystemHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system': {
      id: '/_authenticated/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AuthenticatedSystemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock-transfers': {
      id: '/_authenticated/stock-transfers'
      path: '/stock-transfers'
      fullPath: '/stock-transfers'
      preLoaderRoute: typeof AuthenticatedStockTransfersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seeds': {
      id: '/_authenticated/seeds'
      path: '/seeds'
      fullPath: '/seeds'
      preLoaderRoute: typeof AuthenticatedSeedsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales-reps': {
      id: '/_authenticated/sales-reps'
      path: '/sales-reps'
      fullPath: '/sales-reps'
      preLoaderRoute: typeof AuthenticatedSalesRepsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receipts': {
      id: '/_authenticated/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof AuthenticatedReceiptsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotes': {
      id: '/_authenticated/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof AuthenticatedQuotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchases': {
      id: '/_authenticated/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AuthenticatedPurchasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pricing': {
      id: '/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedPricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pesticides': {
      id: '/_authenticated/pesticides'
      path: '/pesticides'
      fullPath: '/pesticides'
      preLoaderRoute: typeof AuthenticatedPesticidesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loyalty': {
      id: '/_authenticated/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof AuthenticatedLoyaltyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr': {
      id: '/_authenticated/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AuthenticatedHrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fleet': {
      id: '/_authenticated/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof AuthenticatedFleetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fertilizers': {
      id: '/_authenticated/fertilizers'
      path: '/fertilizers'
      fullPath: '/fertilizers'
      preLoaderRoute: typeof AuthenticatedFertilizersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipment': {
      id: '/_authenticated/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof AuthenticatedEquipmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/debts': {
      id: '/_authenticated/debts'
      path: '/debts'
      fullPath: '/debts'
      preLoaderRoute: typeof AuthenticatedDebtsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company-settings': {
      id: '/_authenticated/company-settings'
      path: '/company-settings'
      fullPath: '/company-settings'
      preLoaderRoute: typeof AuthenticatedCompanySettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checks': {
      id: '/_authenticated/checks'
      path: '/checks'
      fullPath: '/checks'
      preLoaderRoute: typeof AuthenticatedChecksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cash-boxes': {
      id: '/_authenticated/cash-boxes'
      path: '/cash-boxes'
      fullPath: '/cash-boxes'
      preLoaderRoute: typeof AuthenticatedCashBoxesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/branches': {
      id: '/_authenticated/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AuthenticatedBranchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/barcodes': {
      id: '/_authenticated/barcodes'
      path: '/barcodes'
      fullPath: '/barcodes'
      preLoaderRoute: typeof AuthenticatedBarcodesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/banks': {
      id: '/_authenticated/banks'
      path: '/banks'
      fullPath: '/banks'
      preLoaderRoute: typeof AuthenticatedBanksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agri': {
      id: '/_authenticated/agri'
      path: '/agri'
      fullPath: '/agri'
      preLoaderRoute: typeof AuthenticatedAgriRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounting': {
      id: '/_authenticated/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AuthenticatedAccountingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/': {
      id: '/_authenticated/system/'
      path: '/'
      fullPath: '/system/'
      preLoaderRoute: typeof AuthenticatedSystemIndexRouteImport
      parentRoute: typeof AuthenticatedSystemRoute
    }
    '/shop/product/$id': {
      id: '/shop/product/$id'
      path: '/product/$id'
      fullPath: '/shop/product/$id'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_authenticated/system/users': {
      id: '/_authenticated/system/users'
      path: '/users'
      fullPath: '/system/users'
      preLoaderRoute: typeof AuthenticatedSystemUsersRouteImport
      parentRoute: typeof AuthenticatedSystemRoute
    }
    '/_authenticated/system/plans': {
      id: '/_authenticated/system/plans'
      path: '/plans'
      fullPath: '/system/plans'
      preLoaderRoute: typeof AuthenticatedSystemPlansRouteImport
      parentRoute: typeof AuthenticatedSystemRoute
    }
    '/_authenticated/system/permissions': {
      id: '/_authenticated/system/permissions'
      path: '/permissions'
      fullPath: '/system/permissions'
      preLoaderRoute: typeof AuthenticatedSystemPermissionsRouteImport
      parentRoute: typeof AuthenticatedSystemRoute
    }
    '/_authenticated/system/organizations': {
      id: '/_authenticated/system/organizations'
      path: '/organizations'
      fullPath: '/system/organizations'
      preLoaderRoute: typeof AuthenticatedSystemOrganizationsRouteImport
      parentRoute: typeof AuthenticatedSystemRoute
    }
    '/_authenticated/system/licenses': {
      id: '/_authenticated/system/licenses'
      path: '/licenses'
      fullPath: '/system/licenses'
      preLoaderRoute: typeof AuthenticatedSystemLicensesRouteImport
      parentRoute: typeof AuthenticatedSystemRoute
    }
    '/_authenticated/system/audit': {
      id: '/_authenticated/system/audit'
      path: '/audit'
      fullPath: '/system/audit'
      preLoaderRoute: typeof AuthenticatedSystemAuditRouteImport
      parentRoute: typeof AuthenticatedSystemRoute
    }
    '/_authenticated/sales-reps/visits': {
      id: '/_authenticated/sales-reps/visits'
      path: '/visits'
      fullPath: '/sales-reps/visits'
      preLoaderRoute: typeof AuthenticatedSalesRepsVisitsRouteImport
      parentRoute: typeof AuthenticatedSalesRepsRoute
    }
    '/_authenticated/sales-reps/list': {
      id: '/_authenticated/sales-reps/list'
      path: '/list'
      fullPath: '/sales-reps/list'
      preLoaderRoute: typeof AuthenticatedSalesRepsListRouteImport
      parentRoute: typeof AuthenticatedSalesRepsRoute
    }
    '/_authenticated/sales-reps/commissions': {
      id: '/_authenticated/sales-reps/commissions'
      path: '/commissions'
      fullPath: '/sales-reps/commissions'
      preLoaderRoute: typeof AuthenticatedSalesRepsCommissionsRouteImport
      parentRoute: typeof AuthenticatedSalesRepsRoute
    }
    '/_authenticated/reports/live': {
      id: '/_authenticated/reports/live'
      path: '/live'
      fullPath: '/reports/live'
      preLoaderRoute: typeof AuthenticatedReportsLiveRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/hr/payroll': {
      id: '/_authenticated/hr/payroll'
      path: '/payroll'
      fullPath: '/hr/payroll'
      preLoaderRoute: typeof AuthenticatedHrPayrollRouteImport
      parentRoute: typeof AuthenticatedHrRoute
    }
    '/_authenticated/hr/leaves': {
      id: '/_authenticated/hr/leaves'
      path: '/leaves'
      fullPath: '/hr/leaves'
      preLoaderRoute: typeof AuthenticatedHrLeavesRouteImport
      parentRoute: typeof AuthenticatedHrRoute
    }
    '/_authenticated/hr/employees': {
      id: '/_authenticated/hr/employees'
      path: '/employees'
      fullPath: '/hr/employees'
      preLoaderRoute: typeof AuthenticatedHrEmployeesRouteImport
      parentRoute: typeof AuthenticatedHrRoute
    }
    '/_authenticated/hr/documents': {
      id: '/_authenticated/hr/documents'
      path: '/documents'
      fullPath: '/hr/documents'
      preLoaderRoute: typeof AuthenticatedHrDocumentsRouteImport
      parentRoute: typeof AuthenticatedHrRoute
    }
    '/_authenticated/hr/attendance': {
      id: '/_authenticated/hr/attendance'
      path: '/attendance'
      fullPath: '/hr/attendance'
      preLoaderRoute: typeof AuthenticatedHrAttendanceRouteImport
      parentRoute: typeof AuthenticatedHrRoute
    }
    '/_authenticated/fleet/vehicles': {
      id: '/_authenticated/fleet/vehicles'
      path: '/vehicles'
      fullPath: '/fleet/vehicles'
      preLoaderRoute: typeof AuthenticatedFleetVehiclesRouteImport
      parentRoute: typeof AuthenticatedFleetRoute
    }
    '/_authenticated/fleet/trips': {
      id: '/_authenticated/fleet/trips'
      path: '/trips'
      fullPath: '/fleet/trips'
      preLoaderRoute: typeof AuthenticatedFleetTripsRouteImport
      parentRoute: typeof AuthenticatedFleetRoute
    }
    '/_authenticated/fleet/tracking': {
      id: '/_authenticated/fleet/tracking'
      path: '/tracking'
      fullPath: '/fleet/tracking'
      preLoaderRoute: typeof AuthenticatedFleetTrackingRouteImport
      parentRoute: typeof AuthenticatedFleetRoute
    }
    '/_authenticated/fleet/maintenance': {
      id: '/_authenticated/fleet/maintenance'
      path: '/maintenance'
      fullPath: '/fleet/maintenance'
      preLoaderRoute: typeof AuthenticatedFleetMaintenanceRouteImport
      parentRoute: typeof AuthenticatedFleetRoute
    }
    '/_authenticated/fleet/fuel': {
      id: '/_authenticated/fleet/fuel'
      path: '/fuel'
      fullPath: '/fleet/fuel'
      preLoaderRoute: typeof AuthenticatedFleetFuelRouteImport
      parentRoute: typeof AuthenticatedFleetRoute
    }
    '/_authenticated/fleet/drivers': {
      id: '/_authenticated/fleet/drivers'
      path: '/drivers'
      fullPath: '/fleet/drivers'
      preLoaderRoute: typeof AuthenticatedFleetDriversRouteImport
      parentRoute: typeof AuthenticatedFleetRoute
    }
    '/_authenticated/dashboards/warehouse': {
      id: '/_authenticated/dashboards/warehouse'
      path: '/dashboards/warehouse'
      fullPath: '/dashboards/warehouse'
      preLoaderRoute: typeof AuthenticatedDashboardsWarehouseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboards/sales': {
      id: '/_authenticated/dashboards/sales'
      path: '/dashboards/sales'
      fullPath: '/dashboards/sales'
      preLoaderRoute: typeof AuthenticatedDashboardsSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboards/hr': {
      id: '/_authenticated/dashboards/hr'
      path: '/dashboards/hr'
      fullPath: '/dashboards/hr'
      preLoaderRoute: typeof AuthenticatedDashboardsHrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboards/fleet': {
      id: '/_authenticated/dashboards/fleet'
      path: '/dashboards/fleet'
      fullPath: '/dashboards/fleet'
      preLoaderRoute: typeof AuthenticatedDashboardsFleetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboards/finance': {
      id: '/_authenticated/dashboards/finance'
      path: '/dashboards/finance'
      fullPath: '/dashboards/finance'
      preLoaderRoute: typeof AuthenticatedDashboardsFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboards/executive': {
      id: '/_authenticated/dashboards/executive'
      path: '/dashboards/executive'
      fullPath: '/dashboards/executive'
      preLoaderRoute: typeof AuthenticatedDashboardsExecutiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agri/treatments': {
      id: '/_authenticated/agri/treatments'
      path: '/treatments'
      fullPath: '/agri/treatments'
      preLoaderRoute: typeof AuthenticatedAgriTreatmentsRouteImport
      parentRoute: typeof AuthenticatedAgriRoute
    }
    '/_authenticated/agri/plants': {
      id: '/_authenticated/agri/plants'
      path: '/plants'
      fullPath: '/agri/plants'
      preLoaderRoute: typeof AuthenticatedAgriPlantsRouteImport
      parentRoute: typeof AuthenticatedAgriRoute
    }
    '/_authenticated/agri/pests': {
      id: '/_authenticated/agri/pests'
      path: '/pests'
      fullPath: '/agri/pests'
      preLoaderRoute: typeof AuthenticatedAgriPestsRouteImport
      parentRoute: typeof AuthenticatedAgriRoute
    }
    '/_authenticated/agri/diseases': {
      id: '/_authenticated/agri/diseases'
      path: '/diseases'
      fullPath: '/agri/diseases'
      preLoaderRoute: typeof AuthenticatedAgriDiseasesRouteImport
      parentRoute: typeof AuthenticatedAgriRoute
    }
    '/_authenticated/accounting/taxes': {
      id: '/_authenticated/accounting/taxes'
      path: '/taxes'
      fullPath: '/accounting/taxes'
      preLoaderRoute: typeof AuthenticatedAccountingTaxesRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/reports': {
      id: '/_authenticated/accounting/reports'
      path: '/reports'
      fullPath: '/accounting/reports'
      preLoaderRoute: typeof AuthenticatedAccountingReportsRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/periods': {
      id: '/_authenticated/accounting/periods'
      path: '/periods'
      fullPath: '/accounting/periods'
      preLoaderRoute: typeof AuthenticatedAccountingPeriodsRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/ledger': {
      id: '/_authenticated/accounting/ledger'
      path: '/ledger'
      fullPath: '/accounting/ledger'
      preLoaderRoute: typeof AuthenticatedAccountingLedgerRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/journal': {
      id: '/_authenticated/accounting/journal'
      path: '/journal'
      fullPath: '/accounting/journal'
      preLoaderRoute: typeof AuthenticatedAccountingJournalRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/chart': {
      id: '/_authenticated/accounting/chart'
      path: '/chart'
      fullPath: '/accounting/chart'
      preLoaderRoute: typeof AuthenticatedAccountingChartRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
  }
}

interface AuthenticatedAccountingRouteChildren {
  AuthenticatedAccountingChartRoute: typeof AuthenticatedAccountingChartRoute
  AuthenticatedAccountingJournalRoute: typeof AuthenticatedAccountingJournalRoute
  AuthenticatedAccountingLedgerRoute: typeof AuthenticatedAccountingLedgerRoute
  AuthenticatedAccountingPeriodsRoute: typeof AuthenticatedAccountingPeriodsRoute
  AuthenticatedAccountingReportsRoute: typeof AuthenticatedAccountingReportsRoute
  AuthenticatedAccountingTaxesRoute: typeof AuthenticatedAccountingTaxesRoute
}

const AuthenticatedAccountingRouteChildren: AuthenticatedAccountingRouteChildren =
  {
    AuthenticatedAccountingChartRoute: AuthenticatedAccountingChartRoute,
    AuthenticatedAccountingJournalRoute: AuthenticatedAccountingJournalRoute,
    AuthenticatedAccountingLedgerRoute: AuthenticatedAccountingLedgerRoute,
    AuthenticatedAccountingPeriodsRoute: AuthenticatedAccountingPeriodsRoute,
    AuthenticatedAccountingReportsRoute: AuthenticatedAccountingReportsRoute,
    AuthenticatedAccountingTaxesRoute: AuthenticatedAccountingTaxesRoute,
  }

const AuthenticatedAccountingRouteWithChildren =
  AuthenticatedAccountingRoute._addFileChildren(
    AuthenticatedAccountingRouteChildren,
  )

interface AuthenticatedAgriRouteChildren {
  AuthenticatedAgriDiseasesRoute: typeof AuthenticatedAgriDiseasesRoute
  AuthenticatedAgriPestsRoute: typeof AuthenticatedAgriPestsRoute
  AuthenticatedAgriPlantsRoute: typeof AuthenticatedAgriPlantsRoute
  AuthenticatedAgriTreatmentsRoute: typeof AuthenticatedAgriTreatmentsRoute
}

const AuthenticatedAgriRouteChildren: AuthenticatedAgriRouteChildren = {
  AuthenticatedAgriDiseasesRoute: AuthenticatedAgriDiseasesRoute,
  AuthenticatedAgriPestsRoute: AuthenticatedAgriPestsRoute,
  AuthenticatedAgriPlantsRoute: AuthenticatedAgriPlantsRoute,
  AuthenticatedAgriTreatmentsRoute: AuthenticatedAgriTreatmentsRoute,
}

const AuthenticatedAgriRouteWithChildren =
  AuthenticatedAgriRoute._addFileChildren(AuthenticatedAgriRouteChildren)

interface AuthenticatedFleetRouteChildren {
  AuthenticatedFleetDriversRoute: typeof AuthenticatedFleetDriversRoute
  AuthenticatedFleetFuelRoute: typeof AuthenticatedFleetFuelRoute
  AuthenticatedFleetMaintenanceRoute: typeof AuthenticatedFleetMaintenanceRoute
  AuthenticatedFleetTrackingRoute: typeof AuthenticatedFleetTrackingRoute
  AuthenticatedFleetTripsRoute: typeof AuthenticatedFleetTripsRoute
  AuthenticatedFleetVehiclesRoute: typeof AuthenticatedFleetVehiclesRoute
}

const AuthenticatedFleetRouteChildren: AuthenticatedFleetRouteChildren = {
  AuthenticatedFleetDriversRoute: AuthenticatedFleetDriversRoute,
  AuthenticatedFleetFuelRoute: AuthenticatedFleetFuelRoute,
  AuthenticatedFleetMaintenanceRoute: AuthenticatedFleetMaintenanceRoute,
  AuthenticatedFleetTrackingRoute: AuthenticatedFleetTrackingRoute,
  AuthenticatedFleetTripsRoute: AuthenticatedFleetTripsRoute,
  AuthenticatedFleetVehiclesRoute: AuthenticatedFleetVehiclesRoute,
}

const AuthenticatedFleetRouteWithChildren =
  AuthenticatedFleetRoute._addFileChildren(AuthenticatedFleetRouteChildren)

interface AuthenticatedHrRouteChildren {
  AuthenticatedHrAttendanceRoute: typeof AuthenticatedHrAttendanceRoute
  AuthenticatedHrDocumentsRoute: typeof AuthenticatedHrDocumentsRoute
  AuthenticatedHrEmployeesRoute: typeof AuthenticatedHrEmployeesRoute
  AuthenticatedHrLeavesRoute: typeof AuthenticatedHrLeavesRoute
  AuthenticatedHrPayrollRoute: typeof AuthenticatedHrPayrollRoute
}

const AuthenticatedHrRouteChildren: AuthenticatedHrRouteChildren = {
  AuthenticatedHrAttendanceRoute: AuthenticatedHrAttendanceRoute,
  AuthenticatedHrDocumentsRoute: AuthenticatedHrDocumentsRoute,
  AuthenticatedHrEmployeesRoute: AuthenticatedHrEmployeesRoute,
  AuthenticatedHrLeavesRoute: AuthenticatedHrLeavesRoute,
  AuthenticatedHrPayrollRoute: AuthenticatedHrPayrollRoute,
}

const AuthenticatedHrRouteWithChildren = AuthenticatedHrRoute._addFileChildren(
  AuthenticatedHrRouteChildren,
)

interface AuthenticatedReportsRouteChildren {
  AuthenticatedReportsLiveRoute: typeof AuthenticatedReportsLiveRoute
}

const AuthenticatedReportsRouteChildren: AuthenticatedReportsRouteChildren = {
  AuthenticatedReportsLiveRoute: AuthenticatedReportsLiveRoute,
}

const AuthenticatedReportsRouteWithChildren =
  AuthenticatedReportsRoute._addFileChildren(AuthenticatedReportsRouteChildren)

interface AuthenticatedSalesRepsRouteChildren {
  AuthenticatedSalesRepsCommissionsRoute: typeof AuthenticatedSalesRepsCommissionsRoute
  AuthenticatedSalesRepsListRoute: typeof AuthenticatedSalesRepsListRoute
  AuthenticatedSalesRepsVisitsRoute: typeof AuthenticatedSalesRepsVisitsRoute
}

const AuthenticatedSalesRepsRouteChildren: AuthenticatedSalesRepsRouteChildren =
  {
    AuthenticatedSalesRepsCommissionsRoute:
      AuthenticatedSalesRepsCommissionsRoute,
    AuthenticatedSalesRepsListRoute: AuthenticatedSalesRepsListRoute,
    AuthenticatedSalesRepsVisitsRoute: AuthenticatedSalesRepsVisitsRoute,
  }

const AuthenticatedSalesRepsRouteWithChildren =
  AuthenticatedSalesRepsRoute._addFileChildren(
    AuthenticatedSalesRepsRouteChildren,
  )

interface AuthenticatedSystemRouteChildren {
  AuthenticatedSystemAuditRoute: typeof AuthenticatedSystemAuditRoute
  AuthenticatedSystemLicensesRoute: typeof AuthenticatedSystemLicensesRoute
  AuthenticatedSystemOrganizationsRoute: typeof AuthenticatedSystemOrganizationsRoute
  AuthenticatedSystemPermissionsRoute: typeof AuthenticatedSystemPermissionsRoute
  AuthenticatedSystemPlansRoute: typeof AuthenticatedSystemPlansRoute
  AuthenticatedSystemUsersRoute: typeof AuthenticatedSystemUsersRoute
  AuthenticatedSystemIndexRoute: typeof AuthenticatedSystemIndexRoute
}

const AuthenticatedSystemRouteChildren: AuthenticatedSystemRouteChildren = {
  AuthenticatedSystemAuditRoute: AuthenticatedSystemAuditRoute,
  AuthenticatedSystemLicensesRoute: AuthenticatedSystemLicensesRoute,
  AuthenticatedSystemOrganizationsRoute: AuthenticatedSystemOrganizationsRoute,
  AuthenticatedSystemPermissionsRoute: AuthenticatedSystemPermissionsRoute,
  AuthenticatedSystemPlansRoute: AuthenticatedSystemPlansRoute,
  AuthenticatedSystemUsersRoute: AuthenticatedSystemUsersRoute,
  AuthenticatedSystemIndexRoute: AuthenticatedSystemIndexRoute,
}

const AuthenticatedSystemRouteWithChildren =
  AuthenticatedSystemRoute._addFileChildren(AuthenticatedSystemRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountingRoute: typeof AuthenticatedAccountingRouteWithChildren
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAgriRoute: typeof AuthenticatedAgriRouteWithChildren
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedBanksRoute: typeof AuthenticatedBanksRoute
  AuthenticatedBarcodesRoute: typeof AuthenticatedBarcodesRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedBranchesRoute: typeof AuthenticatedBranchesRoute
  AuthenticatedCashBoxesRoute: typeof AuthenticatedCashBoxesRoute
  AuthenticatedChecksRoute: typeof AuthenticatedChecksRoute
  AuthenticatedCompanySettingsRoute: typeof AuthenticatedCompanySettingsRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDebtsRoute: typeof AuthenticatedDebtsRoute
  AuthenticatedEquipmentRoute: typeof AuthenticatedEquipmentRoute
  AuthenticatedFertilizersRoute: typeof AuthenticatedFertilizersRoute
  AuthenticatedFleetRoute: typeof AuthenticatedFleetRouteWithChildren
  AuthenticatedHrRoute: typeof AuthenticatedHrRouteWithChildren
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedLoyaltyRoute: typeof AuthenticatedLoyaltyRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPesticidesRoute: typeof AuthenticatedPesticidesRoute
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
  AuthenticatedPricingRoute: typeof AuthenticatedPricingRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedPurchasesRoute: typeof AuthenticatedPurchasesRoute
  AuthenticatedQuotesRoute: typeof AuthenticatedQuotesRoute
  AuthenticatedReceiptsRoute: typeof AuthenticatedReceiptsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRouteWithChildren
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedSalesRepsRoute: typeof AuthenticatedSalesRepsRouteWithChildren
  AuthenticatedSeedsRoute: typeof AuthenticatedSeedsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStockTransfersRoute: typeof AuthenticatedStockTransfersRoute
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedSystemRoute: typeof AuthenticatedSystemRouteWithChildren
  AuthenticatedSystemHealthRoute: typeof AuthenticatedSystemHealthRoute
  AuthenticatedToolsImportExportRoute: typeof AuthenticatedToolsImportExportRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedWarehousesRoute: typeof AuthenticatedWarehousesRoute
  AuthenticatedDashboardsExecutiveRoute: typeof AuthenticatedDashboardsExecutiveRoute
  AuthenticatedDashboardsFinanceRoute: typeof AuthenticatedDashboardsFinanceRoute
  AuthenticatedDashboardsFleetRoute: typeof AuthenticatedDashboardsFleetRoute
  AuthenticatedDashboardsHrRoute: typeof AuthenticatedDashboardsHrRoute
  AuthenticatedDashboardsSalesRoute: typeof AuthenticatedDashboardsSalesRoute
  AuthenticatedDashboardsWarehouseRoute: typeof AuthenticatedDashboardsWarehouseRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountingRoute: AuthenticatedAccountingRouteWithChildren,
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAgriRoute: AuthenticatedAgriRouteWithChildren,
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedBanksRoute: AuthenticatedBanksRoute,
  AuthenticatedBarcodesRoute: AuthenticatedBarcodesRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedBranchesRoute: AuthenticatedBranchesRoute,
  AuthenticatedCashBoxesRoute: AuthenticatedCashBoxesRoute,
  AuthenticatedChecksRoute: AuthenticatedChecksRoute,
  AuthenticatedCompanySettingsRoute: AuthenticatedCompanySettingsRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDebtsRoute: AuthenticatedDebtsRoute,
  AuthenticatedEquipmentRoute: AuthenticatedEquipmentRoute,
  AuthenticatedFertilizersRoute: AuthenticatedFertilizersRoute,
  AuthenticatedFleetRoute: AuthenticatedFleetRouteWithChildren,
  AuthenticatedHrRoute: AuthenticatedHrRouteWithChildren,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedLoyaltyRoute: AuthenticatedLoyaltyRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPesticidesRoute: AuthenticatedPesticidesRoute,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
  AuthenticatedPricingRoute: AuthenticatedPricingRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedPurchasesRoute: AuthenticatedPurchasesRoute,
  AuthenticatedQuotesRoute: AuthenticatedQuotesRoute,
  AuthenticatedReceiptsRoute: AuthenticatedReceiptsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRouteWithChildren,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedSalesRepsRoute: AuthenticatedSalesRepsRouteWithChildren,
  AuthenticatedSeedsRoute: AuthenticatedSeedsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStockTransfersRoute: AuthenticatedStockTransfersRoute,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedSystemRoute: AuthenticatedSystemRouteWithChildren,
  AuthenticatedSystemHealthRoute: AuthenticatedSystemHealthRoute,
  AuthenticatedToolsImportExportRoute: AuthenticatedToolsImportExportRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedWarehousesRoute: AuthenticatedWarehousesRoute,
  AuthenticatedDashboardsExecutiveRoute: AuthenticatedDashboardsExecutiveRoute,
  AuthenticatedDashboardsFinanceRoute: AuthenticatedDashboardsFinanceRoute,
  AuthenticatedDashboardsFleetRoute: AuthenticatedDashboardsFleetRoute,
  AuthenticatedDashboardsHrRoute: AuthenticatedDashboardsHrRoute,
  AuthenticatedDashboardsSalesRoute: AuthenticatedDashboardsSalesRoute,
  AuthenticatedDashboardsWarehouseRoute: AuthenticatedDashboardsWarehouseRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ShopRouteChildren {
  ShopCartRoute: typeof ShopCartRoute
  ShopCheckoutRoute: typeof ShopCheckoutRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopProductIdRoute: typeof ShopProductIdRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopCartRoute: ShopCartRoute,
  ShopCheckoutRoute: ShopCheckoutRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopProductIdRoute: ShopProductIdRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShopRoute: ShopRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
