/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWarehousesRouteImport } from './routes/_authenticated/warehouses'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSeedsRouteImport } from './routes/_authenticated/seeds'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedReceiptsRouteImport } from './routes/_authenticated/receipts'
import { Route as AuthenticatedQuotesRouteImport } from './routes/_authenticated/quotes'
import { Route as AuthenticatedPurchasesRouteImport } from './routes/_authenticated/purchases'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedPricingRouteImport } from './routes/_authenticated/pricing'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated/pos'
import { Route as AuthenticatedPesticidesRouteImport } from './routes/_authenticated/pesticides'
import { Route as AuthenticatedLoyaltyRouteImport } from './routes/_authenticated/loyalty'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedFertilizersRouteImport } from './routes/_authenticated/fertilizers'
import { Route as AuthenticatedEquipmentRouteImport } from './routes/_authenticated/equipment'
import { Route as AuthenticatedDebtsRouteImport } from './routes/_authenticated/debts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedBranchesRouteImport } from './routes/_authenticated/branches'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedAgriRouteImport } from './routes/_authenticated/agri'
import { Route as AuthenticatedAccountingRouteImport } from './routes/_authenticated/accounting'
import { Route as AuthenticatedAgriTreatmentsRouteImport } from './routes/_authenticated/agri.treatments'
import { Route as AuthenticatedAgriPlantsRouteImport } from './routes/_authenticated/agri.plants'
import { Route as AuthenticatedAgriPestsRouteImport } from './routes/_authenticated/agri.pests'
import { Route as AuthenticatedAgriDiseasesRouteImport } from './routes/_authenticated/agri.diseases'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWarehousesRoute = AuthenticatedWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeedsRoute = AuthenticatedSeedsRouteImport.update({
  id: '/seeds',
  path: '/seeds',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReceiptsRoute = AuthenticatedReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotesRoute = AuthenticatedQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchasesRoute = AuthenticatedPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPesticidesRoute = AuthenticatedPesticidesRouteImport.update({
  id: '/pesticides',
  path: '/pesticides',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLoyaltyRoute = AuthenticatedLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFertilizersRoute =
  AuthenticatedFertilizersRouteImport.update({
    id: '/fertilizers',
    path: '/fertilizers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipmentRoute = AuthenticatedEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDebtsRoute = AuthenticatedDebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBranchesRoute = AuthenticatedBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgriRoute = AuthenticatedAgriRouteImport.update({
  id: '/agri',
  path: '/agri',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountingRoute = AuthenticatedAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgriTreatmentsRoute =
  AuthenticatedAgriTreatmentsRouteImport.update({
    id: '/treatments',
    path: '/treatments',
    getParentRoute: () => AuthenticatedAgriRoute,
  } as any)
const AuthenticatedAgriPlantsRoute = AuthenticatedAgriPlantsRouteImport.update({
  id: '/plants',
  path: '/plants',
  getParentRoute: () => AuthenticatedAgriRoute,
} as any)
const AuthenticatedAgriPestsRoute = AuthenticatedAgriPestsRouteImport.update({
  id: '/pests',
  path: '/pests',
  getParentRoute: () => AuthenticatedAgriRoute,
} as any)
const AuthenticatedAgriDiseasesRoute =
  AuthenticatedAgriDiseasesRouteImport.update({
    id: '/diseases',
    path: '/diseases',
    getParentRoute: () => AuthenticatedAgriRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accounting': typeof AuthenticatedAccountingRoute
  '/agri': typeof AuthenticatedAgriRouteWithChildren
  '/ai': typeof AuthenticatedAiRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/debts': typeof AuthenticatedDebtsRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/fertilizers': typeof AuthenticatedFertilizersRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/loyalty': typeof AuthenticatedLoyaltyRoute
  '/pesticides': typeof AuthenticatedPesticidesRoute
  '/pos': typeof AuthenticatedPosRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/products': typeof AuthenticatedProductsRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/quotes': typeof AuthenticatedQuotesRoute
  '/receipts': typeof AuthenticatedReceiptsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/seeds': typeof AuthenticatedSeedsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/users': typeof AuthenticatedUsersRoute
  '/warehouses': typeof AuthenticatedWarehousesRoute
  '/agri/diseases': typeof AuthenticatedAgriDiseasesRoute
  '/agri/pests': typeof AuthenticatedAgriPestsRoute
  '/agri/plants': typeof AuthenticatedAgriPlantsRoute
  '/agri/treatments': typeof AuthenticatedAgriTreatmentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accounting': typeof AuthenticatedAccountingRoute
  '/agri': typeof AuthenticatedAgriRouteWithChildren
  '/ai': typeof AuthenticatedAiRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/debts': typeof AuthenticatedDebtsRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/fertilizers': typeof AuthenticatedFertilizersRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/loyalty': typeof AuthenticatedLoyaltyRoute
  '/pesticides': typeof AuthenticatedPesticidesRoute
  '/pos': typeof AuthenticatedPosRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/products': typeof AuthenticatedProductsRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/quotes': typeof AuthenticatedQuotesRoute
  '/receipts': typeof AuthenticatedReceiptsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/seeds': typeof AuthenticatedSeedsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/users': typeof AuthenticatedUsersRoute
  '/warehouses': typeof AuthenticatedWarehousesRoute
  '/agri/diseases': typeof AuthenticatedAgriDiseasesRoute
  '/agri/pests': typeof AuthenticatedAgriPestsRoute
  '/agri/plants': typeof AuthenticatedAgriPlantsRoute
  '/agri/treatments': typeof AuthenticatedAgriTreatmentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/accounting': typeof AuthenticatedAccountingRoute
  '/_authenticated/agri': typeof AuthenticatedAgriRouteWithChildren
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/branches': typeof AuthenticatedBranchesRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/debts': typeof AuthenticatedDebtsRoute
  '/_authenticated/equipment': typeof AuthenticatedEquipmentRoute
  '/_authenticated/fertilizers': typeof AuthenticatedFertilizersRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/loyalty': typeof AuthenticatedLoyaltyRoute
  '/_authenticated/pesticides': typeof AuthenticatedPesticidesRoute
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/_authenticated/pricing': typeof AuthenticatedPricingRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/purchases': typeof AuthenticatedPurchasesRoute
  '/_authenticated/quotes': typeof AuthenticatedQuotesRoute
  '/_authenticated/receipts': typeof AuthenticatedReceiptsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/seeds': typeof AuthenticatedSeedsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/warehouses': typeof AuthenticatedWarehousesRoute
  '/_authenticated/agri/diseases': typeof AuthenticatedAgriDiseasesRoute
  '/_authenticated/agri/pests': typeof AuthenticatedAgriPestsRoute
  '/_authenticated/agri/plants': typeof AuthenticatedAgriPlantsRoute
  '/_authenticated/agri/treatments': typeof AuthenticatedAgriTreatmentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/accounting'
    | '/agri'
    | '/ai'
    | '/branches'
    | '/customers'
    | '/dashboard'
    | '/debts'
    | '/equipment'
    | '/fertilizers'
    | '/inventory'
    | '/loyalty'
    | '/pesticides'
    | '/pos'
    | '/pricing'
    | '/products'
    | '/purchases'
    | '/quotes'
    | '/receipts'
    | '/reports'
    | '/sales'
    | '/seeds'
    | '/settings'
    | '/suppliers'
    | '/users'
    | '/warehouses'
    | '/agri/diseases'
    | '/agri/pests'
    | '/agri/plants'
    | '/agri/treatments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/accounting'
    | '/agri'
    | '/ai'
    | '/branches'
    | '/customers'
    | '/dashboard'
    | '/debts'
    | '/equipment'
    | '/fertilizers'
    | '/inventory'
    | '/loyalty'
    | '/pesticides'
    | '/pos'
    | '/pricing'
    | '/products'
    | '/purchases'
    | '/quotes'
    | '/receipts'
    | '/reports'
    | '/sales'
    | '/seeds'
    | '/settings'
    | '/suppliers'
    | '/users'
    | '/warehouses'
    | '/agri/diseases'
    | '/agri/pests'
    | '/agri/plants'
    | '/agri/treatments'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/accounting'
    | '/_authenticated/agri'
    | '/_authenticated/ai'
    | '/_authenticated/branches'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/debts'
    | '/_authenticated/equipment'
    | '/_authenticated/fertilizers'
    | '/_authenticated/inventory'
    | '/_authenticated/loyalty'
    | '/_authenticated/pesticides'
    | '/_authenticated/pos'
    | '/_authenticated/pricing'
    | '/_authenticated/products'
    | '/_authenticated/purchases'
    | '/_authenticated/quotes'
    | '/_authenticated/receipts'
    | '/_authenticated/reports'
    | '/_authenticated/sales'
    | '/_authenticated/seeds'
    | '/_authenticated/settings'
    | '/_authenticated/suppliers'
    | '/_authenticated/users'
    | '/_authenticated/warehouses'
    | '/_authenticated/agri/diseases'
    | '/_authenticated/agri/pests'
    | '/_authenticated/agri/plants'
    | '/_authenticated/agri/treatments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/warehouses': {
      id: '/_authenticated/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof AuthenticatedWarehousesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seeds': {
      id: '/_authenticated/seeds'
      path: '/seeds'
      fullPath: '/seeds'
      preLoaderRoute: typeof AuthenticatedSeedsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receipts': {
      id: '/_authenticated/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof AuthenticatedReceiptsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotes': {
      id: '/_authenticated/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof AuthenticatedQuotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchases': {
      id: '/_authenticated/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AuthenticatedPurchasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pricing': {
      id: '/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedPricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pesticides': {
      id: '/_authenticated/pesticides'
      path: '/pesticides'
      fullPath: '/pesticides'
      preLoaderRoute: typeof AuthenticatedPesticidesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loyalty': {
      id: '/_authenticated/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof AuthenticatedLoyaltyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fertilizers': {
      id: '/_authenticated/fertilizers'
      path: '/fertilizers'
      fullPath: '/fertilizers'
      preLoaderRoute: typeof AuthenticatedFertilizersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipment': {
      id: '/_authenticated/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof AuthenticatedEquipmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/debts': {
      id: '/_authenticated/debts'
      path: '/debts'
      fullPath: '/debts'
      preLoaderRoute: typeof AuthenticatedDebtsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/branches': {
      id: '/_authenticated/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AuthenticatedBranchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agri': {
      id: '/_authenticated/agri'
      path: '/agri'
      fullPath: '/agri'
      preLoaderRoute: typeof AuthenticatedAgriRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounting': {
      id: '/_authenticated/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AuthenticatedAccountingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agri/treatments': {
      id: '/_authenticated/agri/treatments'
      path: '/treatments'
      fullPath: '/agri/treatments'
      preLoaderRoute: typeof AuthenticatedAgriTreatmentsRouteImport
      parentRoute: typeof AuthenticatedAgriRoute
    }
    '/_authenticated/agri/plants': {
      id: '/_authenticated/agri/plants'
      path: '/plants'
      fullPath: '/agri/plants'
      preLoaderRoute: typeof AuthenticatedAgriPlantsRouteImport
      parentRoute: typeof AuthenticatedAgriRoute
    }
    '/_authenticated/agri/pests': {
      id: '/_authenticated/agri/pests'
      path: '/pests'
      fullPath: '/agri/pests'
      preLoaderRoute: typeof AuthenticatedAgriPestsRouteImport
      parentRoute: typeof AuthenticatedAgriRoute
    }
    '/_authenticated/agri/diseases': {
      id: '/_authenticated/agri/diseases'
      path: '/diseases'
      fullPath: '/agri/diseases'
      preLoaderRoute: typeof AuthenticatedAgriDiseasesRouteImport
      parentRoute: typeof AuthenticatedAgriRoute
    }
  }
}

interface AuthenticatedAgriRouteChildren {
  AuthenticatedAgriDiseasesRoute: typeof AuthenticatedAgriDiseasesRoute
  AuthenticatedAgriPestsRoute: typeof AuthenticatedAgriPestsRoute
  AuthenticatedAgriPlantsRoute: typeof AuthenticatedAgriPlantsRoute
  AuthenticatedAgriTreatmentsRoute: typeof AuthenticatedAgriTreatmentsRoute
}

const AuthenticatedAgriRouteChildren: AuthenticatedAgriRouteChildren = {
  AuthenticatedAgriDiseasesRoute: AuthenticatedAgriDiseasesRoute,
  AuthenticatedAgriPestsRoute: AuthenticatedAgriPestsRoute,
  AuthenticatedAgriPlantsRoute: AuthenticatedAgriPlantsRoute,
  AuthenticatedAgriTreatmentsRoute: AuthenticatedAgriTreatmentsRoute,
}

const AuthenticatedAgriRouteWithChildren =
  AuthenticatedAgriRoute._addFileChildren(AuthenticatedAgriRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountingRoute: typeof AuthenticatedAccountingRoute
  AuthenticatedAgriRoute: typeof AuthenticatedAgriRouteWithChildren
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedBranchesRoute: typeof AuthenticatedBranchesRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDebtsRoute: typeof AuthenticatedDebtsRoute
  AuthenticatedEquipmentRoute: typeof AuthenticatedEquipmentRoute
  AuthenticatedFertilizersRoute: typeof AuthenticatedFertilizersRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedLoyaltyRoute: typeof AuthenticatedLoyaltyRoute
  AuthenticatedPesticidesRoute: typeof AuthenticatedPesticidesRoute
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
  AuthenticatedPricingRoute: typeof AuthenticatedPricingRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedPurchasesRoute: typeof AuthenticatedPurchasesRoute
  AuthenticatedQuotesRoute: typeof AuthenticatedQuotesRoute
  AuthenticatedReceiptsRoute: typeof AuthenticatedReceiptsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedSeedsRoute: typeof AuthenticatedSeedsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedWarehousesRoute: typeof AuthenticatedWarehousesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountingRoute: AuthenticatedAccountingRoute,
  AuthenticatedAgriRoute: AuthenticatedAgriRouteWithChildren,
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedBranchesRoute: AuthenticatedBranchesRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDebtsRoute: AuthenticatedDebtsRoute,
  AuthenticatedEquipmentRoute: AuthenticatedEquipmentRoute,
  AuthenticatedFertilizersRoute: AuthenticatedFertilizersRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedLoyaltyRoute: AuthenticatedLoyaltyRoute,
  AuthenticatedPesticidesRoute: AuthenticatedPesticidesRoute,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
  AuthenticatedPricingRoute: AuthenticatedPricingRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedPurchasesRoute: AuthenticatedPurchasesRoute,
  AuthenticatedQuotesRoute: AuthenticatedQuotesRoute,
  AuthenticatedReceiptsRoute: AuthenticatedReceiptsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedSeedsRoute: AuthenticatedSeedsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedWarehousesRoute: AuthenticatedWarehousesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
