-- 1) Fix mutable search_path (qualify pgcrypto in extensions schema)
CREATE OR REPLACE FUNCTION public.generate_license_key()
RETURNS text
LANGUAGE sql
SET search_path = public, extensions
AS $$
  SELECT 'HAYTAM-' || upper(encode(extensions.gen_random_bytes(4),'hex')) || '-' || upper(encode(extensions.gen_random_bytes(4),'hex')) || '-' || upper(encode(extensions.gen_random_bytes(4),'hex'))
$$;

-- 2) Explicit deny-all policies on backend-only tables
DROP POLICY IF EXISTS "no client access" ON public.auth_attempts;
CREATE POLICY "no client access" ON public.auth_attempts FOR ALL TO authenticated, anon USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "no client access" ON public.password_resets;
CREATE POLICY "no client access" ON public.password_resets FOR ALL TO authenticated, anon USING (false) WITH CHECK (false);

-- 3) FK covering indexes
CREATE INDEX IF NOT EXISTS idx_accounts_parent_id ON public.accounts (parent_id);
CREATE INDEX IF NOT EXISTS idx_activity_log_user_id ON public.activity_log (user_id);
CREATE INDEX IF NOT EXISTS idx_agri_disease_images_disease_id ON public.agri_disease_images (disease_id);
CREATE INDEX IF NOT EXISTS idx_agri_pest_images_pest_id ON public.agri_pest_images (pest_id);
CREATE INDEX IF NOT EXISTS idx_agri_plant_categories_parent_id ON public.agri_plant_categories (parent_id);
CREATE INDEX IF NOT EXISTS idx_agri_plant_diseases_plant_id ON public.agri_plant_diseases (plant_id);
CREATE INDEX IF NOT EXISTS idx_agri_plant_pests_plant_id ON public.agri_plant_pests (plant_id);
CREATE INDEX IF NOT EXISTS idx_agri_plant_varieties_plant_id ON public.agri_plant_varieties (plant_id);
CREATE INDEX IF NOT EXISTS idx_agri_plants_category_id ON public.agri_plants (category_id);
CREATE INDEX IF NOT EXISTS idx_agri_treatment_products_treatment_id ON public.agri_treatment_products (treatment_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_organization_id ON public.audit_logs (organization_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id ON public.audit_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_bank_accounts_account_id ON public.bank_accounts (account_id);
CREATE INDEX IF NOT EXISTS idx_bank_transactions_user_id ON public.bank_transactions (user_id);
CREATE INDEX IF NOT EXISTS idx_bank_transactions_counter_bank_id ON public.bank_transactions (counter_bank_id);
CREATE INDEX IF NOT EXISTS idx_bank_transactions_bank_id ON public.bank_transactions (bank_id);
CREATE INDEX IF NOT EXISTS idx_branch_members_branch_id ON public.branch_members (branch_id);
CREATE INDEX IF NOT EXISTS idx_branches_manager_id ON public.branches (manager_id);
CREATE INDEX IF NOT EXISTS idx_cash_boxes_account_id ON public.cash_boxes (account_id);
CREATE INDEX IF NOT EXISTS idx_cash_boxes_branch_id ON public.cash_boxes (branch_id);
CREATE INDEX IF NOT EXISTS idx_cash_movements_user_id ON public.cash_movements (user_id);
CREATE INDEX IF NOT EXISTS idx_cash_movements_box_id ON public.cash_movements (box_id);
CREATE INDEX IF NOT EXISTS idx_cash_movements_counter_box_id ON public.cash_movements (counter_box_id);
CREATE INDEX IF NOT EXISTS idx_categories_parent_id ON public.categories (parent_id);
CREATE INDEX IF NOT EXISTS idx_checks_user_id ON public.checks (user_id);
CREATE INDEX IF NOT EXISTS idx_checks_bank_id ON public.checks (bank_id);
CREATE INDEX IF NOT EXISTS idx_coupon_redemptions_customer_id ON public.coupon_redemptions (customer_id);
CREATE INDEX IF NOT EXISTS idx_coupon_redemptions_coupon_id ON public.coupon_redemptions (coupon_id);
CREATE INDEX IF NOT EXISTS idx_customers_created_by ON public.customers (created_by);
CREATE INDEX IF NOT EXISTS idx_fiscal_periods_closed_by ON public.fiscal_periods (closed_by);
CREATE INDEX IF NOT EXISTS idx_fleet_drivers_employee_id ON public.fleet_drivers (employee_id);
CREATE INDEX IF NOT EXISTS idx_fleet_fuel_logs_driver_id ON public.fleet_fuel_logs (driver_id);
CREATE INDEX IF NOT EXISTS idx_fleet_fuel_logs_vehicle_id ON public.fleet_fuel_logs (vehicle_id);
CREATE INDEX IF NOT EXISTS idx_fleet_gps_positions_vehicle_id ON public.fleet_gps_positions (vehicle_id);
CREATE INDEX IF NOT EXISTS idx_fleet_maintenance_vehicle_id ON public.fleet_maintenance (vehicle_id);
CREATE INDEX IF NOT EXISTS idx_fleet_trips_driver_id ON public.fleet_trips (driver_id);
CREATE INDEX IF NOT EXISTS idx_fleet_trips_vehicle_id ON public.fleet_trips (vehicle_id);
CREATE INDEX IF NOT EXISTS idx_fleet_vehicles_branch_id ON public.fleet_vehicles (branch_id);
CREATE INDEX IF NOT EXISTS idx_hr_attendance_employee_id ON public.hr_attendance (employee_id);
CREATE INDEX IF NOT EXISTS idx_hr_bonuses_employee_id ON public.hr_bonuses (employee_id);
CREATE INDEX IF NOT EXISTS idx_hr_documents_employee_id ON public.hr_documents (employee_id);
CREATE INDEX IF NOT EXISTS idx_hr_employees_department_id ON public.hr_employees (department_id);
CREATE INDEX IF NOT EXISTS idx_hr_employees_branch_id ON public.hr_employees (branch_id);
CREATE INDEX IF NOT EXISTS idx_hr_employees_position_id ON public.hr_employees (position_id);
CREATE INDEX IF NOT EXISTS idx_hr_leaves_employee_id ON public.hr_leaves (employee_id);
CREATE INDEX IF NOT EXISTS idx_hr_payroll_employee_id ON public.hr_payroll (employee_id);
CREATE INDEX IF NOT EXISTS idx_hr_positions_department_id ON public.hr_positions (department_id);
CREATE INDEX IF NOT EXISTS idx_journal_entries_period_id ON public.journal_entries (period_id);
CREATE INDEX IF NOT EXISTS idx_journal_entries_created_by ON public.journal_entries (created_by);
CREATE INDEX IF NOT EXISTS idx_journal_lines_entry_id ON public.journal_lines (entry_id);
CREATE INDEX IF NOT EXISTS idx_journal_lines_account_id ON public.journal_lines (account_id);
CREATE INDEX IF NOT EXISTS idx_licenses_organization_id ON public.licenses (organization_id);
CREATE INDEX IF NOT EXISTS idx_licenses_created_by ON public.licenses (created_by);
CREATE INDEX IF NOT EXISTS idx_licenses_plan_id ON public.licenses (plan_id);
CREATE INDEX IF NOT EXISTS idx_loyalty_transactions_customer_id ON public.loyalty_transactions (customer_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON public.notifications (user_id);
CREATE INDEX IF NOT EXISTS idx_organization_members_organization_id ON public.organization_members (organization_id);
CREATE INDEX IF NOT EXISTS idx_organizations_owner_user_id ON public.organizations (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_password_resets_user_id ON public.password_resets (user_id);
CREATE INDEX IF NOT EXISTS idx_price_list_items_category_id ON public.price_list_items (category_id);
CREATE INDEX IF NOT EXISTS idx_price_list_items_product_id ON public.price_list_items (product_id);
CREATE INDEX IF NOT EXISTS idx_price_list_items_price_list_id ON public.price_list_items (price_list_id);
CREATE INDEX IF NOT EXISTS idx_product_batches_product_id ON public.product_batches (product_id);
CREATE INDEX IF NOT EXISTS idx_product_documents_product_id ON public.product_documents (product_id);
CREATE INDEX IF NOT EXISTS idx_product_images_product_id ON public.product_images (product_id);
CREATE INDEX IF NOT EXISTS idx_product_locations_product_id ON public.product_locations (product_id);
CREATE INDEX IF NOT EXISTS idx_products_created_by ON public.products (created_by);
CREATE INDEX IF NOT EXISTS idx_products_supplier_id ON public.products (supplier_id);
CREATE INDEX IF NOT EXISTS idx_products_category_id ON public.products (category_id);
CREATE INDEX IF NOT EXISTS idx_profiles_id ON public.profiles (id);
CREATE INDEX IF NOT EXISTS idx_purchase_order_items_po_id ON public.purchase_order_items (po_id);
CREATE INDEX IF NOT EXISTS idx_purchase_order_items_product_id ON public.purchase_order_items (product_id);
CREATE INDEX IF NOT EXISTS idx_purchase_orders_branch_id ON public.purchase_orders (branch_id);
CREATE INDEX IF NOT EXISTS idx_purchase_orders_warehouse_id ON public.purchase_orders (warehouse_id);
CREATE INDEX IF NOT EXISTS idx_purchase_orders_supplier_id ON public.purchase_orders (supplier_id);
CREATE INDEX IF NOT EXISTS idx_purchase_orders_created_by ON public.purchase_orders (created_by);
CREATE INDEX IF NOT EXISTS idx_purchase_orders_approved_by ON public.purchase_orders (approved_by);
CREATE INDEX IF NOT EXISTS idx_purchase_receipt_items_receipt_id ON public.purchase_receipt_items (receipt_id);
CREATE INDEX IF NOT EXISTS idx_purchase_receipt_items_product_id ON public.purchase_receipt_items (product_id);
CREATE INDEX IF NOT EXISTS idx_purchase_receipts_supplier_id ON public.purchase_receipts (supplier_id);
CREATE INDEX IF NOT EXISTS idx_purchase_receipts_po_id ON public.purchase_receipts (po_id);
CREATE INDEX IF NOT EXISTS idx_purchase_receipts_received_by ON public.purchase_receipts (received_by);
CREATE INDEX IF NOT EXISTS idx_purchase_receipts_warehouse_id ON public.purchase_receipts (warehouse_id);
CREATE INDEX IF NOT EXISTS idx_receipts_created_by ON public.receipts (created_by);
CREATE INDEX IF NOT EXISTS idx_sale_installments_sale_id ON public.sale_installments (sale_id);
CREATE INDEX IF NOT EXISTS idx_sale_items_product_id ON public.sale_items (product_id);
CREATE INDEX IF NOT EXISTS idx_sale_items_sale_id ON public.sale_items (sale_id);
CREATE INDEX IF NOT EXISTS idx_sale_payments_sale_id ON public.sale_payments (sale_id);
CREATE INDEX IF NOT EXISTS idx_sale_payments_user_id ON public.sale_payments (user_id);
CREATE INDEX IF NOT EXISTS idx_sales_coupon_id ON public.sales (coupon_id);
CREATE INDEX IF NOT EXISTS idx_sales_cashier_id ON public.sales (cashier_id);
CREATE INDEX IF NOT EXISTS idx_sales_warehouse_id ON public.sales (warehouse_id);
CREATE INDEX IF NOT EXISTS idx_sales_branch_id ON public.sales (branch_id);
CREATE INDEX IF NOT EXISTS idx_sales_customer_id ON public.sales (customer_id);
CREATE INDEX IF NOT EXISTS idx_sales_sales_rep_id ON public.sales (sales_rep_id);
CREATE INDEX IF NOT EXISTS idx_sales_parent_sale_id ON public.sales (parent_sale_id);
CREATE INDEX IF NOT EXISTS idx_sales_commissions_rep_id ON public.sales_commissions (rep_id);
CREATE INDEX IF NOT EXISTS idx_sales_reps_branch_id ON public.sales_reps (branch_id);
CREATE INDEX IF NOT EXISTS idx_sales_reps_employee_id ON public.sales_reps (employee_id);
CREATE INDEX IF NOT EXISTS idx_sales_visits_rep_id ON public.sales_visits (rep_id);
CREATE INDEX IF NOT EXISTS idx_sales_visits_customer_id ON public.sales_visits (customer_id);
CREATE INDEX IF NOT EXISTS idx_stock_movements_product_id ON public.stock_movements (product_id);
CREATE INDEX IF NOT EXISTS idx_stock_movements_to_warehouse_id ON public.stock_movements (to_warehouse_id);
CREATE INDEX IF NOT EXISTS idx_stock_movements_to_bin_id ON public.stock_movements (to_bin_id);
CREATE INDEX IF NOT EXISTS idx_stock_movements_from_warehouse_id ON public.stock_movements (from_warehouse_id);
CREATE INDEX IF NOT EXISTS idx_stock_movements_from_bin_id ON public.stock_movements (from_bin_id);
CREATE INDEX IF NOT EXISTS idx_stock_movements_batch_id ON public.stock_movements (batch_id);
CREATE INDEX IF NOT EXISTS idx_stock_movements_user_id ON public.stock_movements (user_id);
CREATE INDEX IF NOT EXISTS idx_stock_transfer_items_transfer_id ON public.stock_transfer_items (transfer_id);
CREATE INDEX IF NOT EXISTS idx_stock_transfer_items_product_id ON public.stock_transfer_items (product_id);
CREATE INDEX IF NOT EXISTS idx_stock_transfers_to_warehouse_id ON public.stock_transfers (to_warehouse_id);
CREATE INDEX IF NOT EXISTS idx_stock_transfers_from_warehouse_id ON public.stock_transfers (from_warehouse_id);
CREATE INDEX IF NOT EXISTS idx_stock_transfers_created_by ON public.stock_transfers (created_by);
CREATE INDEX IF NOT EXISTS idx_stocktake_lines_stocktake_id ON public.stocktake_lines (stocktake_id);
CREATE INDEX IF NOT EXISTS idx_stocktake_lines_bin_id ON public.stocktake_lines (bin_id);
CREATE INDEX IF NOT EXISTS idx_stocktake_lines_product_id ON public.stocktake_lines (product_id);
CREATE INDEX IF NOT EXISTS idx_stocktakes_warehouse_id ON public.stocktakes (warehouse_id);
CREATE INDEX IF NOT EXISTS idx_stocktakes_created_by ON public.stocktakes (created_by);
CREATE INDEX IF NOT EXISTS idx_subscriptions_user_id ON public.subscriptions (user_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_plan_id ON public.subscriptions (plan_id);
CREATE INDEX IF NOT EXISTS idx_supplier_invoices_supplier_id ON public.supplier_invoices (supplier_id);
CREATE INDEX IF NOT EXISTS idx_supplier_invoices_po_id ON public.supplier_invoices (po_id);
CREATE INDEX IF NOT EXISTS idx_supplier_payments_supplier_id ON public.supplier_payments (supplier_id);
CREATE INDEX IF NOT EXISTS idx_supplier_payments_invoice_id ON public.supplier_payments (invoice_id);
CREATE INDEX IF NOT EXISTS idx_suppliers_created_by ON public.suppliers (created_by);
CREATE INDEX IF NOT EXISTS idx_user_roles_user_id ON public.user_roles (user_id);
CREATE INDEX IF NOT EXISTS idx_warehouse_aisles_zone_id ON public.warehouse_aisles (zone_id);
CREATE INDEX IF NOT EXISTS idx_warehouse_bins_shelf_id ON public.warehouse_bins (shelf_id);
CREATE INDEX IF NOT EXISTS idx_warehouse_racks_aisle_id ON public.warehouse_racks (aisle_id);
CREATE INDEX IF NOT EXISTS idx_warehouse_shelves_rack_id ON public.warehouse_shelves (rack_id);
CREATE INDEX IF NOT EXISTS idx_warehouse_zones_warehouse_id ON public.warehouse_zones (warehouse_id);
CREATE INDEX IF NOT EXISTS idx_warehouses_branch_id ON public.warehouses (branch_id);